### ISSUE TITLE
Hi losewheel and thanks

### ISSUE THREAD

**Issue by mattruffoni** [loosewheel/lwscratch#1]
Hi, I'm Matteo an italian teacher. I installed a minetest server for my students and I added lwscratch. I'd like to trnaslate in italian you manual and upload it to wikibooks. 
Can I do it?
I'll need to screenshot some picture of your mod and upload to wikimedia commons. 
Do you leave me doing that?
Tks Matteo
[https://it.wikibooks.org/wiki/Software_libero_a_scuola/Minetest#Mod:_lwscratch_(Programmazione_a_blocchi)]

**Comment by loosewheel** [comment]
Yes. That is Ok.
